# Generated by Django 2.1.7 on 2019-03-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='template',
        ),
        migrations.AddField(
            model_name='category',
            name='detail_post_template',
            field=models.CharField(default='news/detail_post__template_default.html', max_length=100, verbose_name='Шаблон для постов detail'),
        ),
        migrations.AddField(
            model_name='category',
            name='short_post_template',
            field=models.CharField(default='news/short_post__template_default.html', max_length=100, verbose_name='Шаблон для постов short'),
        ),
    ]
