# Generated by Django 2.1.7 on 2019-03-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190223_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='moderation',
            field=models.BooleanField(default=False, verbose_name='Разрешено к публикации'),
        ),
    ]
