# Generated by Django 2.1.7 on 2019-03-10 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_comment_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='do_publish',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=True, verbose_name='Опубликовать'),
        ),
        migrations.AddField(
            model_name='post',
            name='edited',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата редактирования'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_main',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='post',
            name='show_for_all',
            field=models.BooleanField(choices=[(True, 'Для всех'), (False, 'Только для зарегистрированных')], default=True, verbose_name='Показывать для всех'),
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='', max_length=100, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='post',
            name='template',
            field=models.CharField(default='post_template_default.html', max_length=100, verbose_name='Используемый шаблон'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
